export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';

export const LIST_TODO_REQUEST = 'LIST_TODO_REQUEST';
export const LIST_TODO_SUCCESS = 'LIST_TODO_SUCCESS';
export const LIST_TODO_FAILURE = 'LIST_TODO_FAILURE';
export const LIST_TODO_REMOVE = 'LIST_TODO_REMOVE';

export const REMOVE_TODO_REQUEST = 'REMOVE_TODO_REQUEST';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_FAILURE = 'REMOVE_TODO_FAILURE';

export const INITIALIZE_TODO = 'INITIALIZE_TODO';